### ISSUE TITLE
Windows equivalent of .incbin

### ISSUE THREAD

**Issue by LegalizeAdulthood** [graphitemaster/incbin#34]
Instead of doing the big data array approach when you don't have the .incbin directive, why not use a custom resource type and generate a resource file as well as a source file that loads the data from the resource?

You use a [user-defined resource type](https://docs.microsoft.com/en-us/windows/win32/menurc/user-defined-resource) to point the resource to the binary blob.  Each embedded binary gets its own resource id in the generated resource script and the generated C++ source file loads the resources and obtains pointers to their data.  The code would call [FindResourceA](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-findresourcea) to get the `HRSRC` for the blob and then [LoadResource](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadresource) followed by [LockResource](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-lockresource) to get the pointer to the data and [SizeofResource](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-sizeofresource) to get the data length.

For large binary payloads, this avoids all the compiler processing work of C++ source files of large data arrays.

**Comment by LegalizeAdulthood** [comment]
Note: one wrinkle with this is when the resource is embedded in a DLL, in which case the code that fetches the resources will need to make sure that it uses the result of `LoadLibraryA` on the DLL filename for the `HMODULE` parameter to the resource functions, or it won't locate the resources properly.

**Comment by graphitemaster** [comment]
It's too complicated to support this feature because it involves integration with VS, or at the very least MSBuild. It gets complicated when the project already has a resource file and it requires generating some initialization code. I wanted to keep this as straight forward as possible. Ideally you'd have to do nothing but include this header (as is the case with any compiler but VS.) The reason the tool exists at all is mostly because I could not find a work around that was not intrusive like the resource approach. Still not happy with it but I generally view VS as a black sheep of the family of compilers.
